version: 0.2

env:
  variables:
    CLUSTER_NAME: "cicd-k8s-cluster"          # ชื่อ EKS cluster
    AWS_REGION: "us-east-1"            # Region ที่ใช้
    IMAGE_REPO_NAME: "node-mysql"           # ชื่อ ECR repository
    IMAGE_TAG: "latest"                     # หรือใช้ commit hash: CODEBUILD_RESOLVED_SOURCE_VERSION
    ACCOUNT_ID: "058264398861"               # AWS Account ID ของคุณ

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Checking versions..."
      - node -v
      - npm -v
      - aws --version
      - echo "Installing kubectl..."
      - curl -o kubectl https://amazon-eks.s3.$AWS_REGION.amazonaws.com/$(aws eks describe-cluster --name $CLUSTER_NAME --region $AWS_REGION --query "cluster.version" --output text)/2025-01-17/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo "Updating kubeconfig for EKS..."
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
      - echo "Deploying to EKS..."
      - kubectl set image deployment/node-mysql-deployment node-mysql-container=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG --record
      - kubectl rollout status deployment/node-mysql-deployment
