apiVersion: v1
kind: Service
metadata:
  name: node-mysql-service
  labels:
    app: node-mysql
spec:
  selector:
    app: node-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
